import {defineField, defineType} from 'sanity'
import {CalendarIcon, LinkIcon} from '@sanity/icons'

const descriptionFoto =
  "Dica: Abrir ferramenta 'Crop' para ajustar a imagem e definir o ponto de interesse."

const listaCategoriasPT = [
  {title: 'Programa da Bienal', value: 'Programa da Bienal'},
  {title: 'Programa Convergente', value: 'Programa Convergente'},
  {title: 'Programa de Arquitetura', value: 'Programa de Arquitetura'},
]
const listaCategoriasEN = [
  {title: 'Bienal Programme', value: 'Bienal Programme'},
  {title: 'Convergent Programme', value: 'Convergent Programme'},
  {title: 'Architecture Programme', value: 'Architecture Programme'},
]
const listaTiposPT = [
  {title: 'Abertura', value: 'Abertura'},
  {title: 'Visita', value: 'Visita'},
  {title: 'Workshops & Experiências Criativas', value: 'Workshops & Experiências Criativas'},
  {title: 'Fórum', value: 'Fórum'},
  {title: 'Encruzilhadas', value: 'Encruzilhadas'},
  {title: 'Conversa', value: 'Conversa'},
  {title: 'Performance', value: 'Performance'},
  {title: 'Lançamento', value: 'Lançamento'},
  {title: 'Exposição', value: 'Exposição'},
  {title: 'Instalação', value: 'Instalação'},
  {title: 'Gastronomia', value: 'Gastronomia'},
  {title: 'Intervenção urbana', value: 'Intervenção urbana'},
  {title: 'Poesia expandida', value: 'Poesia expandida'},
  {title: 'Workshop', value: 'Workshop'},
  {title: 'Conferência', value: 'Conferência'},
  {title: 'Lançamento de livro', value: 'Lançamento de livro'},
  {title: 'Ação', value: 'Ação'},
  {title: 'Canto coral', value: 'Canto coral'},
  {title: 'Impressão de Cartazes', value: 'Impressão de Cartazes'},
  {title: 'Ocupação performativa', value: 'Ocupação performativa'},
  {title: 'Caminhada performativa', value: 'Caminhada performativa'},
  {title: 'Instalação com cartazes', value: 'Instalação com cartazes'},
  {title: 'Intervenção', value: 'Intervenção'},
  {title: 'Video-mapping', value: 'Video-mapping'},
  {title: 'Projetos especiais', value: 'Projetos especiais'},
  {title: 'Instalação Sonora', value: 'Instalação Sonora'},
  {title: 'Concerto', value: 'Concerto'},
  {title: 'Poéticas visuais', value: 'Poéticas visuais'},
  {title: 'Transmissão Rádio', value: 'Transmissão Rádio'},
  {title: 'Teatro', value: 'Teatro'},
]
const listaTiposEN = [
  {title: 'Opening', value: 'Opening'},
  {title: 'Visit', value: 'Visit'},
  {title: 'Workshops & Creative Experiences', value: 'Workshops & Creative Experiences'},
  {title: 'Forum', value: 'Forum'},
  {title: 'Crossroads', value: 'Crossroads'},
  {title: 'Talk', value: 'Talk'},
  {title: 'Performance', value: 'Performance'},
  {title: 'Launch', value: 'Launch'},
  {title: 'Exhibition', value: 'Exhibition'},
  {title: 'Installation', value: 'Installation'},
  {title: 'Gastronomy', value: 'Gastronomy'},
  {title: 'Urban intervention', value: 'Urban intervention'},
  {title: 'Expanded Poetry', value: 'Expanded Poetry'},
  {title: 'Workshop', value: 'Workshop'},
  {title: 'Conference', value: 'Conference'},
  {title: 'Book release', value: 'Book release'},
  {title: 'Action', value: 'Action'},
  {title: 'Choral singing', value: 'Choral singing'},
  {title: 'Poster Printing', value: 'Poster Printing'},
  {title: 'Performative occupation', value: 'Performative occupation'},
  {title: 'Performative walk', value: 'Performative walk'},
  {title: 'Poster installation', value: 'Poster installation'},
  {title: 'Intervention', value: 'Intervention'},
  {title: 'Video-mapping', value: 'Video-mapping'},
  {title: 'Special Projects', value: 'Special Projects'},
  {title: 'Sound Installation', value: 'Sound Installation'},
  {title: 'Concert', value: 'Concert'},
  {title: 'Visual Poetics', value: 'Visual Poetics'},
  {title: 'Radio Transmission', value: 'Radio Transmission'},
  {title: 'Theater', value: 'Theater'},
]

export default defineType({
  name: 'evento',
  type: 'document',
  title: 'Evento',
  fieldsets: [
    {name: 'categoria', title: 'Categoria'},
    {name: 'tipo', title: 'Tipo de Evento'},
    {name: 'titulo', title: 'Título'},
    {name: 'datas', title: 'Data(s) em Texto'},
    {name: 'horarioCurto', title: 'Horário Curto'},
    {name: 'horarioLongo', title: 'Horário Longo'},
    {name: 'local', title: 'Local'},
    {name: 'outrosDetalhes', title: 'Outros Detalhes'},
    {name: 'texto', title: 'Conteúdo Textual'},
  ],
  groups: [
    {name: 'pt', title: 'Texto PT'},
    {name: 'en', title: 'Texto EN'},
  ],
  fields: [
    defineField({
      name: 'imagemDestaque',
      title: 'Imagem Destaque',
      type: 'image',
      description: descriptionFoto,
      options: {hotspot: true},
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'categoria_pt',
      title: '🇵🇹 PT',
      type: 'string',
      options: {list: listaCategoriasPT},
      fieldset: 'categoria',
      group: ['pt'],
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'categoria_en',
      title: '🇬🇧 EN',
      type: 'string',
      options: {list: listaCategoriasEN},
      fieldset: 'categoria',
      group: ['en'],
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'tipo_pt',
      title: '🇵🇹 PT',
      type: 'array',
      of: [{type: 'string', options: {list: listaTiposPT}}],
      fieldset: 'tipo',
      group: ['pt'],
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'tipo_en',
      title: '🇬🇧 EN',
      type: 'array',
      of: [{type: 'string', options: {list: listaTiposEN}}],
      fieldset: 'tipo',
      group: ['en'],
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'titulo_pt',
      title: '🇵🇹 PT',
      type: 'string',
      fieldset: 'titulo',
      group: ['pt'],
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'titulo_en',
      title: '🇬🇧 EN',
      type: 'string',
      fieldset: 'titulo',
      group: ['en'],
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: (doc: any, context: any): string => doc.titulo_pt,
        maxLength: 200,
      },
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'textoDatas_pt',
      title: '🇵🇹 PT',
      type: 'string',
      fieldset: 'datas',
      group: ['pt'],
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'textoDatas_en',
      title: '🇬🇧 EN',
      type: 'string',
      fieldset: 'datas',
      group: ['en'],
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'datas',
      title: 'Data(s) para Agenda',
      type: 'array',
      fieldset: 'datas',
      validation: (Rule: any) => Rule.required(),
      of: [
        {
          name: 'listaDatas',
          type: 'object',
          icon: CalendarIcon,
          fields: [
            {
              name: 'dataInicial',
              type: 'date',
              options: {
                dateFormat: 'DD-MM-YYYY',
                calendarTodayLabel: 'Today',
              },
            },
            {
              title: 'É um intervalo de datas?',
              name: 'intervaloDatas',
              type: 'boolean',
              initialValue: false,
            },
            {
              name: 'dataFinal',
              type: 'date',
              options: {
                dateFormat: 'DD-MM-YYYY',
                calendarTodayLabel: 'Today',
              },
              hidden: ({parent}) => !parent?.intervaloDatas,
            },
          ],
          preview: {
            select: {
              dataInicial: 'dataInicial',
              dataFinal: 'dataFinal',
              intervaloDatas: 'intervaloDatas',
            },
            prepare({dataInicial, dataFinal, intervaloDatas}) {
              return {
                title: !intervaloDatas ? dataInicial : `${dataInicial} — ${dataFinal}`,
              }
            },
          },
        },
      ],
    }),
    defineField({
      name: 'horarioCurto_pt',
      title: '🇵🇹 PT',
      type: 'string',
      fieldset: 'horarioCurto',
      group: ['pt'],
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'horarioLongo_pt',
      title: '🇵🇹 PT',
      type: 'text',
      rows: 4,
      fieldset: 'horarioLongo',
      group: ['pt'],
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'horarioCurto_en',
      title: '🇬🇧 EN',
      type: 'string',
      fieldset: 'horarioCurto',
      group: ['en'],
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'horarioLongo_en',
      title: '🇬🇧 EN',
      type: 'text',
      rows: 4,
      fieldset: 'horarioLongo',
      group: ['en'],
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'localNome',
      title: 'Nome do Local',
      type: 'string',
      fieldset: 'local',
      group: ['pt', 'en'],
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'localMorada',
      title: 'Morada do Local',
      type: 'string',
      fieldset: 'local',
      group: ['pt', 'en'],
    }),
    defineField({
      name: 'localURLExterno',
      title: 'Link externo do Local',
      type: 'url',
      description: "OBRIGATÓRIO: Começar com 'http://' ou 'https://'",
      fieldset: 'local',
    }),
    defineField({
      name: 'localURLInterno',
      title: 'Link interno do Local',
      type: 'reference',
      to: {type: 'espaco'},
      fieldset: 'local',
    }),
    defineField({
      name: 'outroDetalhe1_pt',
      title: 'Outro Detalhe 1 🇵🇹 PT',
      description: 'Exemplo: "Duração do evento: 120\'"',
      type: 'string',
      fieldset: 'outrosDetalhes',
      group: ['pt'],
    }),
    defineField({
      name: 'outroDetalhe2_pt',
      title: 'Outro Detalhe 2 🇵🇹 PT',
      description: 'Exemplo: "Público-Alvo: Todos os Públicos"',
      type: 'string',
      fieldset: 'outrosDetalhes',
      group: ['pt'],
    }),
    defineField({
      name: 'outroDetalhe3_pt',
      title: 'Outro Detalhe 3 🇵🇹 PT',
      description: 'Exemplo: "Preço: Gratuito"',
      type: 'string',
      fieldset: 'outrosDetalhes',
      group: ['pt'],
    }),
    defineField({
      name: 'outroDetalhe1_en',
      title: 'Outro Detalhe 1 🇬🇧 EN',
      description: 'Exemplo: "Duração do evento: 120\'"',
      type: 'string',
      fieldset: 'outrosDetalhes',
      group: ['en'],
    }),
    defineField({
      name: 'outroDetalhe2_en',
      title: 'Outro Detalhe 2 🇬🇧 EN',
      description: 'Exemplo: "Público-Alvo: All Audiences"',
      type: 'string',
      fieldset: 'outrosDetalhes',
      group: ['en'],
    }),
    defineField({
      name: 'outroDetalhe3_en',
      title: 'Outro Detalhe 3 🇬🇧 EN',
      description: 'Exemplo: "Preço: Free"',
      type: 'string',
      fieldset: 'outrosDetalhes',
      group: ['en'],
    }),
    defineField({
      name: 'linksExtra',
      title: 'Links Extra',
      description: 'Exemplo: Links do lado direito. Ex: "Formulário" ou "Saber mais"',
      type: 'array',
      of: [
        {
          type: 'object',
          icon: LinkIcon,
          fields: [
            {name: 'linkExtraTexto_pt', title: 'Texto Link Extra🇵🇹 PT', type: 'string'},
            {name: 'linkExtraTexto_en', title: 'Texto Link Extra 🇬🇧 EN', type: 'string'},
            {
              name: 'linkExtraURL',
              title: 'URL/Link',
              type: 'url',
              description: "OBRIGATÓRIO: Começar com 'http://' ou 'https://'",
            },
          ],
        },
      ],
    }),
    defineField({
      name: 'texto_pt',
      title: '🇵🇹 PT',
      type: 'array',
      of: [{type: 'block'}],
      fieldset: 'texto',
      group: ['pt'],
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'texto_en',
      title: '🇬🇧 EN',
      type: 'array',
      of: [{type: 'block'}],
      fieldset: 'texto',
      group: ['en'],
      validation: (Rule: any) => Rule.required(),
    }),
    defineField({
      name: 'listaArtistasManual',
      title: 'Lista de Artistas (Manual)',
      description: 'Artistas que não fazem parte da programação oficial.',
      type: 'array',
      of: [
        {
          type: 'object',
          icon: LinkIcon,
          fields: [
            {name: 'nomeListaArtistasManual_pt', title: 'Nome Artista', type: 'string'},
            {
              name: 'linkListaArtistasManual',
              title: 'URL/Link',
              type: 'url',
              description: "OBRIGATÓRIO: Começar com 'http://' ou 'https://'",
            },
          ],
        },
      ],
    }),
    defineField({
      name: 'artistasRelacionados',
      title: 'Artistas Relacionados',
      type: 'array',
      of: [{type: 'reference', to: {type: 'artista'}}],
    }),
    defineField({
      name: 'eventosRelacionados',
      title: 'Eventos Relacionados',
      type: 'array',
      of: [{type: 'reference', to: {type: 'evento'}}],
    }),

    // TODO: Para quando o sistema de Notícias estiver montado
    // defineField({
    //   name: 'noticiasRelacionadas',
    //   title: 'Notícias Relacionados',
    //   type: 'array',
    //   of: [{type: 'reference', to: {type: 'noticia'}}],
    // }),
  ],
  preview: {
    select: {
      titulo_pt: 'titulo_pt',
      tipo_pt: 'tipo_pt',
      categoria_pt: 'categoria_pt',
      imagemDestaque: 'imagemDestaque',
    },
    prepare({titulo_pt, tipo_pt, categoria_pt, imagemDestaque}) {
      return {
        title: titulo_pt,
        subtitle: `${tipo_pt} - ${categoria_pt}`,
        media: imagemDestaque,
      }
    },
  },
})
